- name: put etc/environment
  template: src=ostro-worker-etc-environment.j2 dest=/etc/environment mode=0644 owner=root group=root

- name: put apt config
  template: src=ostro-worker-etc-apt-apt-conf.j2 dest=/etc/apt/apt.conf mode=0644 owner=root group=root

- name: put apt sources.list
  template: src=ostro-worker-etc-apt-sources-list.j2 dest=/etc/apt/sources.list mode=0644 owner=root group=root

- name: apt-get update
  apt: update_cache=yes cache_valid_time=3600
